### ISSUE TITLE
现在遇到一个新问题

### ISSUE THREAD

**Issue by tfxidian** [Badangel/VMI-based-security-Monitor-in-Virtualized-Environments#2]
我用virt-manager 安装虚拟机Ubuntu时，遇到下面的问题

···
unable to complete install：Failed to connect socket to '/var/run/libvirt/virtlogd-sock' ：No such file or directory

···

我以前不用源码安装libvirt而是直接用apt-get install 命令安装时，从来没有出过这个问题，这次在libvirt源码安装过程中好像也没报任何错误，为什么安装虚拟机的时候出现这个问题了

**Comment by Badangel** [comment]
@tfxidian 你的libvirtd 有没有开启，如果开了在输入命令
`virtlogd -d`
试试

**Comment by tfxidian** [comment]
你好，我又来了。（最近在看毕业论文所以这个就搁置了）。上次感觉出了不少问题，所以我想重新装一下。
1.请问你readconfiguration/libvirt 文件中第一行引用了[利用KVM、QEMU、Libvirt建立并管理虚拟机](http://blog.csdn.net/ThomasWangqiang/article/details/54098350)这个链接，请问是什么意思？是按照这个方法安装好虚拟机，后面再重新用源码安装了libvirt和qemu-2.8.0-rc0吗？
2.请问readconfiguration文件夹下的文件是你的安装顺序吗

对这些不太懂，可能会提出一些比较低水平和奇怪的问题，望见谅。

**Comment by Badangel** [comment]
@tfxidian 不是的，只是我之前在安装依赖的时候做了参考，你也可以按照那个安装。因为源码安装时候会提示安装依赖问题，一个个解决太烦，第二行已经给出了我觉得要安装的所有依赖，你可以直接先安装依赖，再直接通过源码安装就好。kvm搭配libvmi问题很多，因为libvmi是基于xen的，如果你还没深入建议用xen吧。还有我安装的qemu是2.4.0因为有libvmi的补丁，2.8.0你可以试试我不知道可不可以。
